// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.28.1
// source: proto/numbers.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	MaxNumber_RegisterNumber_FullMethodName = "/proto.maxNumber/registerNumber"
)

// MaxNumberClient is the client API for MaxNumber service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MaxNumberClient interface {
	RegisterNumber(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[Number, Max], error)
}

type maxNumberClient struct {
	cc grpc.ClientConnInterface
}

func NewMaxNumberClient(cc grpc.ClientConnInterface) MaxNumberClient {
	return &maxNumberClient{cc}
}

func (c *maxNumberClient) RegisterNumber(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[Number, Max], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &MaxNumber_ServiceDesc.Streams[0], MaxNumber_RegisterNumber_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[Number, Max]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type MaxNumber_RegisterNumberClient = grpc.BidiStreamingClient[Number, Max]

// MaxNumberServer is the server API for MaxNumber service.
// All implementations must embed UnimplementedMaxNumberServer
// for forward compatibility.
type MaxNumberServer interface {
	RegisterNumber(grpc.BidiStreamingServer[Number, Max]) error
	mustEmbedUnimplementedMaxNumberServer()
}

// UnimplementedMaxNumberServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMaxNumberServer struct{}

func (UnimplementedMaxNumberServer) RegisterNumber(grpc.BidiStreamingServer[Number, Max]) error {
	return status.Errorf(codes.Unimplemented, "method RegisterNumber not implemented")
}
func (UnimplementedMaxNumberServer) mustEmbedUnimplementedMaxNumberServer() {}
func (UnimplementedMaxNumberServer) testEmbeddedByValue()                   {}

// UnsafeMaxNumberServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MaxNumberServer will
// result in compilation errors.
type UnsafeMaxNumberServer interface {
	mustEmbedUnimplementedMaxNumberServer()
}

func RegisterMaxNumberServer(s grpc.ServiceRegistrar, srv MaxNumberServer) {
	// If the following call pancis, it indicates UnimplementedMaxNumberServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&MaxNumber_ServiceDesc, srv)
}

func _MaxNumber_RegisterNumber_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(MaxNumberServer).RegisterNumber(&grpc.GenericServerStream[Number, Max]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type MaxNumber_RegisterNumberServer = grpc.BidiStreamingServer[Number, Max]

// MaxNumber_ServiceDesc is the grpc.ServiceDesc for MaxNumber service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MaxNumber_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proto.maxNumber",
	HandlerType: (*MaxNumberServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "registerNumber",
			Handler:       _MaxNumber_RegisterNumber_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "proto/numbers.proto",
}
